CREATE TABLE DIVISA (ABREVIATURA VARCHAR NOT NULL, cambio_euro DOUBLE NOT NULL, NOMBRE VARCHAR NOT NULL, SIMBOLO CHAR, PRIMARY KEY (ABREVIATURA))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
