CREATE TABLE CUENTA (IBAN BIGINT NOT NULL, CODIGO_PAIS VARCHAR(2) NOT NULL, SWIFT VARCHAR, PRIMARY KEY (IBAN))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
