CREATE TABLE CLIENTE (ID BIGINT NOT NULL, DTYPE VARCHAR(31), CIUDAD VARCHAR NOT NULL, CODIGOPOSTAL INTEGER NOT NULL, DIRECCION VARCHAR NOT NULL, FECHA_ALTA DATE NOT NULL, FECHA_BAJA DATE, IDENTIFICACION VARCHAR NOT NULL, PAIS VARCHAR NOT NULL, ESTADO VARCHAR NOT NULL, TIPO_CLIENTE VARCHAR NOT NULL, Razon_Social VARCHAR NOT NULL, APELLIDO VARCHAR(40) NOT NULL, fecha_nacimiento DATE, NOMBRE VARCHAR(30) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
